version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
      time: "04:00"
    reviewers:
      - "wayfusion/qa"
      
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - "npm"
      - "dependencies"
    open-pull-requests-limit: 10  
    reviewers:
      - "wayfusion/qa"
