# configuration spec at https://github.com/actions/labeler/blob/master/README.md
docs:
  - meta/*
  - CHANGELOG.md
  - CONTRIBUTING.md
  - LICENSE
  - README.md
tests:
  - test/**/*
automation:
  - .github/**/*
bash:
  - scripts/**/*
server:
  - api/**/*
components:
  - src/components/*
typings:
  - '*.d.ts'
  