blank_issues_enabled: false
contact_links:
  # - name: Create new issue
  #   url: https://new-issue/
  #   about: Please use the following link to create a new issue.
  - name: Patreon
    url: https://www.patreon.com/
    about: Love this? Please consider supporting us via Patreon.
  - name: Documentation
    url: https://github.com/sergkhl/vue3-typescript-kanban#readme
    about: Read this