---
# https://docs.github.com/en/actions/configuring-and-managing-workflows/configuring-a-workflow
# triggers https://docs.github.com/en/actions/reference/events-that-trigger-workflows
# TODO https://github.com/actions/github-script

name: 'Build & Test'
on:
  push:
    branches: [master]
    paths-ignore:
      - 'docs/**'
  pull_request:
    branches: [master, 'feature/**']

jobs:
  build:
    name: 'Build'
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Use Node.js
        uses: actions/setup-node@v2.1.1
        with:
          node-version: '14'
          check-latest: true

      - name: Install and Build 🔧
        run: |
          npm install
          npm run build

      - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path: |
            dist
            !dist/**/*.md
