---
# https://docs.github.com/en/actions/configuring-and-managing-workflows/configuring-a-workflow
# triggers https://docs.github.com/en/actions/reference/events-that-trigger-workflows
# TODO https://github.com/actions/github-script

name: Build
on:
  push:
    branches: [master]
    paths-ignore:
      - 'docs/**'
  pull_request:
    branches: [master, 'feature/**']

jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Use Node.js
        uses: actions/setup-node@v2.1.1
        with:
          node-version: '14'
          check-latest: true

      - name: Install and Build 🔧
        run: |
          npm install
          npm run build

      # https://github.com/actions/upload-artifact
      - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path: |
            dist
            !dist/**/*.md
          if-no-files-found: error

      - name: Display structure of files
        run: ls -R

  deploy:
    name: Deploy
    needs: Build
    runs-on: ubuntu-20.04
    steps:
      # https://github.com/actions/download-artifact
      - name: Download artifacts
        id: download
        uses: actions/download-artifact@v2
        with:
          name: dist
          path: dist
      - name: Display structure of files
        run: ls -R
      - name: 'Echo download path'
        run: echo ${{steps.download.outputs.download-path}}
      - name: Deploy 🚀
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist

