---
name: 'Deploy'
on:
  # run after
  workflow_run:
    workflows: ['Build & Test']
    types:
      - completed

jobs:
  deploy:
    name: 'Deploy'
    runs-on: ubuntu-20.04
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          name: dist
      - name: Deploy 🚀
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
